backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use backend\models\MapForm;
use backend\models\RemoveForm;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\VarDumper;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */


    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionMap()
    {
        $model = new MapForm();

        if (Yii::$app->request->isPost) {
            $model->one_file = UploadedFile::getInstance($model, 'one_file');
            $model->two_file = UploadedFile::getInstance($model, 'two_file');
            if ($model->upload()) {
                $result = '';

                $first = file_get_contents($model->one_new);
                $first = explode("\n", $first);

                $two = file_get_contents($model->two_new);
                $two = explode("\n", $two);

                foreach ($first as $f) {
                    foreach ($two as $t) {
                        $str = $f . ' ' . $t;
                        $str = str_replace("\r", "", $str);
                        if (substr_count($str, ' ') < 7) {
                            $result .= $str . "\n";
                        }
                    }
                }

                $model->result_name = uniqid() . '.txt';
                $model->result = 'data/map/result/' . $model->result_name;
                file_put_contents(Yii::getAlias('@backend/web/') . $model->result, $result);
                unlink($model->one_new);
                unlink($model->two_new);
            }
        }

        return $this->render('map', ['model' => $model]);
    }

    public function actionRemove()
    {
        $model = new RemoveForm();

        if (Yii::$app->request->isPost) {
            $model->word_file = UploadedFile::getInstance($model, 'word_file');
            $model->minus_file = UploadedFile::getInstance($model, 'minus_file');
            if ($model->upload()) {
                $result = '';

                $first = file_get_contents($model->word_new);
                $first = explode("\n", $first);


                $two = file_get_contents($model->minus_new);
                $two = explode("\n", $two);

                foreach ($first as $f) {
                    $temp = str_replace("\r", "", $f);
                    $temp = str_replace("\n", "", $temp) . ' ';
                    foreach ($two as $t) {
                        $t2 = str_replace("\r", "", $t);
<<<<<<< HEAD
						$t2 = str_replace("\n", "", $t2);
                        if (strpos($temp, $t2 . ' ') === false) {
	
=======
                        if (strpos($f . ' ', $t2 . ' ') === false) {
>>>>>>> 8831d8839ee7b4eba846ec83c9be35fa8f3ace31
                            $temp .= ' -' . $t2;
                        }
                    }
                    $result .= $temp . "\n";
                }

                $model->result_name = uniqid() . '.txt';
                $model->result = 'data/remove/result/' . $model->result_name;
                file_put_contents(Yii::getAlias('@backend/web/') . $model->result, $result);
                unlink($model->word_new);
                unlink($model->minus_new);
            }
        }

        return $this->render('remove', ['model' => $model]);

    }

    public function actionClear($type, $file)
    {
        unlink(Yii::getAlias("@backend/web/data/{$type}/result/") . $file);
        $this->redirect('/site/' . $type);
    }

}

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/map.php
<?php
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\MapForm */


$this->title = 'Слияние';
?>
<div class="site-index">
    <div class="body-content">

        <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

        <?= $form->field($model, 'one_file')->fileInput() ?>

        <?= $form->field($model, 'two_file')->fileInput() ?>


        <button>Submit</button>

        <?php if ($model->result) : ?>
            <div>Result: <a href="/<?=$model->result;?>"><?=$model->result;?></a></div>

            <div>Remove: <a href="<?= Url::to(['/site/clear', 'type' => 'map', 'file' => $model->result_name]);?>">link</a></div>

        <?php endif; ?>

        <?php ActiveForm::end() ?>

    </div>
</div>

backend/views/site/remove.php
<?php
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\RemoveForm */


$this->title = 'Минуса';
?>
<div class="site-index">
    <div class="body-content">

        <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

        <?= $form->field($model, 'word_file')->fileInput() ?>

        <?= $form->field($model, 'minus_file')->fileInput() ?>


        <button>Submit</button>

        <?php if ($model->result) : ?>
            <div>Result: <a href="/<?=$model->result;?>"><?=$model->result;?></a></div>

            <div>Remove: <a href="<?= Url::to(['/site/clear', 'type' => 'remove', 'file' => $model->result_name]);?>">link</a></div>
        <?php endif; ?>

        <?php ActiveForm::end() ?>

    </div>
</div>